name: Running unit tests

# Comment out the 'on' block
#on:
#  push:
#    branch:
#      - main
      
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run our unittest script
        run: python testing_blank.py -v
